import { ITopicData } from "../Types/interfaces";

export const topicListExample: ITopicData[] = [
   {
      id: 123,
      icon: "language",
      name: "English / German",
      data: [
         {
            id: 1,
            word: "Long",
            meaning: "Lang",
            rate: 0,
            img: "https://images.pexels.com/photos/3801347/pexels-photo-3801347.jpeg?auto=compress&cs=tinysrgb&w=1200",
         },
         {
            id: 2,
            word: "Tall",
            meaning: "Groß",
            rate: 0,
            img: "https://images.pexels.com/photos/618079/pexels-photo-618079.jpeg?auto=compress&cs=tinysrgb&w=1200",
         },
         {
            id: 3,
            word: "Small",
            meaning: "Klein",
            rate: 0,
            img: "https://images.pexels.com/photos/1692984/pexels-photo-1692984.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
         },
         {
            id: 4,
            word: "Brief",
            meaning: "Kurz",
            rate: 0,
            img: "https://images.pexels.com/photos/1438404/pexels-photo-1438404.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
         },
         {
            id: 5,
            word: "Bad",
            meaning: "Schlecht",
            rate: 0,
            img: "https://images.pexels.com/photos/18148284/pexels-photo-18148284.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
         },
         {
            id: 6,
            word: "Calm",
            meaning: "Ruhig",
            rate: 0,
            img: "https://images.pexels.com/photos/33582/sunrise-phu-quoc-island-ocean.jpg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
         },
         {
            id: 7,
            word: "Strong",
            meaning: "Stark",
            rate: 0,
            img: "https://images.pexels.com/photos/949126/pexels-photo-949126.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
         },
         {
            id: 8,
            word: "Weak",
            meaning: "Schwach",
            rate: 0,
            img: "https://cdn.pixabay.com/photo/2022/08/20/02/26/weak-7398114_1280.png",
         },
         {
            id: 9,
            word: "Quiet",
            meaning: "Leise",
            rate: 0,
            img: "https://images.pexels.com/photos/3768723/pexels-photo-3768723.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
         },
         {
            id: 10,
            word: "Sad",
            meaning: "Traurig",
            rate: 0,
            img: "https://images.pexels.com/photos/47090/baby-tears-small-child-sad-47090.jpeg?auto=compress&cs=tinysrgb&w=1200",
         },
         {
            id: 10,
            word: "Funny",
            meaning: "Lustig",
            rate: 5,
            img: "https://images.pexels.com/photos/1629781/pexels-photo-1629781.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
         },
         {
            id: 11,
            word: "Far",
            meaning: "Weit",
            rate: 0,
            img: "https://images.pexels.com/photos/248159/pexels-photo-248159.jpeg?auto=compress&cs=tinysrgb&w=1200",
         },
         {
            id: 12,
            word: "Near",
            meaning: "Nahe",
            rate: 0,
            img: "https://images.pexels.com/photos/249097/pexels-photo-249097.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
         },
         {
            id: 13,
            word: "Deep",
            meaning: "Tief",
            rate: 0,
            img: "https://images.pexels.com/photos/54306/underwater-divers-helmet-diver-historically-54306.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
         },
         {
            id: 14,
            word: "Clean",
            meaning: "Sauber",
            rate: 0,
            img: "https://images.pexels.com/photos/1571459/pexels-photo-1571459.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
         },
         {
            id: 15,
            word: "Dirty",
            meaning: "Schmutzig",
            rate: 0,
            img: "https://images.pexels.com/photos/162397/lost-places-factory-old-lapsed-162397.jpeg?auto=compress&cs=tinysrgb&w=1200",
         },
      ],
   },
];
